services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    profiles:
      - dev
      - prod

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - "./localstack:/docker-entrypoint-initaws.d"
    profiles:
      - dev
      - prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/your_db_name
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - mongo
      - localstack
    profiles:
      - prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    profiles:
      - prod

volumes:
  mongo-data:


